# Generated by Django 5.2.17 on 2026-09-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=40)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(null=True)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=200)),
                ("alerted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Lauf",
                "verbose_name_plural": "Läufe",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["job", "-started_at"], name="jobs_run_job_started"),
                    models.Index(fields=["-finished_at"], name="jobs_run_finished"),
                ],
            },
        ),
    ]
