# Generated by Django 5.2.17 on 2026-09-26 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.DateField()),
                ("channel", models.CharField(max_length=20)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("unverified", "E-Mail nicht bestätigt"),
                            ("booked", "Termin wahrgenommen oder vergeben"),
                            ("declined", "abgelehnt"),
                            ("withdrawn", "zurückgezogen"),
                            ("expired", "verfallen"),
                            ("cancelled_by_patient", "vom Patienten abgesagt"),
                            ("cancelled_by_practice", "von der Praxis abgesagt"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "lead_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "kein Termin"),
                            ("0-2", "bis 2 Tage"),
                            ("3-7", "3 bis 7 Tage"),
                            ("8-14", "8 bis 14 Tage"),
                            ("15+", "mehr als 14 Tage"),
                        ],
                        max_length=8,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "appointment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="appointments.appointmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zählerstand",
                "verbose_name_plural": "Zählerstände",
                "ordering": ["week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "week",
                            "appointment_type",
                            "channel",
                            "outcome",
                            "lead_time",
                        ),
                        name="reporting_statistic_one_row_per_group",
                    )
                ],
            },
        ),
    ]
