# Generated by Django 5.2.17 on 2026-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.DateField()),
                ("mode", models.CharField(max_length=16)),
                ("outcome", models.CharField(max_length=20)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Zählerstand Anrufe",
                "verbose_name_plural": "Zählerstände Anrufe",
                "ordering": ["week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("week", "mode", "outcome"),
                        name="reporting_callstatistic_one_row_per_group",
                    )
                ],
            },
        ),
    ]
