# Generated by Django 5.2.17 on 2026-09-26 11:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "angesehen"),
                            ("list", "Liste angesehen"),
                            ("search", "gesucht"),
                            ("create", "angelegt"),
                            ("update", "geändert"),
                            ("export", "exportiert"),
                            ("print", "gedruckt"),
                            ("download", "heruntergeladen"),
                        ],
                        max_length=16,
                    ),
                ),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("patient_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("result_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Protokolleintrag",
                "verbose_name_plural": "Protokolleinträge",
                "ordering": ["-at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                [
                                    "view",
                                    "list",
                                    "search",
                                    "create",
                                    "update",
                                    "export",
                                    "print",
                                    "download",
                                ],
                            )
                        ),
                        name="audit_accesslogentry_action_valid",
                    )
                ],
            },
        ),
    ]
