# Generated by Django 5.2.17 on 2026-09-27 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accesslogentry",
            name="audit_accesslogentry_action_valid",
        ),
        migrations.AlterField(
            model_name="accesslogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "angesehen"),
                    ("list", "Liste angesehen"),
                    ("search", "gesucht"),
                    ("create", "angelegt"),
                    ("update", "geändert"),
                    ("export", "exportiert"),
                    ("print", "gedruckt"),
                    ("download", "heruntergeladen"),
                    ("emergency_access", "Notfallzugriff"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="accesslogentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "view",
                            "list",
                            "search",
                            "create",
                            "update",
                            "export",
                            "print",
                            "download",
                            "emergency_access",
                        ],
                    )
                ),
                name="audit_accesslogentry_action_valid",
            ),
        ),
    ]
