# Generated by Django 5.2.17 on 2026-09-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opening", "geöffnet"),
                            ("consultation", "Sprechzeit"),
                        ],
                        max_length=16,
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("opens", models.TimeField()),
                ("closes", models.TimeField()),
            ],
            options={
                "verbose_name": "Öffnungszeit",
                "verbose_name_plural": "Öffnungszeiten",
                "ordering": ["kind", "weekday", "opens"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["opening", "consultation"])),
                        name="practice_openinghours_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weekday__lte", 6)),
                        name="practice_openinghours_weekday_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("closes__gt", models.F("opens"))),
                        name="practice_openinghours_closes_after_opens",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("doctor", "Ärztin/Arzt"),
                            ("room", "Raum"),
                            ("device", "Gerät"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Ressource",
                "verbose_name_plural": "Ressourcen",
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["doctor", "room", "device"])),
                        name="practice_resource_kind_valid",
                    )
                ],
            },
        ),
    ]
