# Generated by Django 5.2.17 on 2026-09-26 11:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("public_name", models.CharField(max_length=100)),
                ("bookable_online", models.BooleanField(default=False)),
                ("default_duration", models.DurationField()),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Terminart",
                "verbose_name_plural": "Terminarten",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "E-Mail nicht bestätigt"),
                            ("open", "offen"),
                            ("scheduled", "Termin vergeben"),
                            ("declined", "abgelehnt"),
                            ("withdrawn", "zurückgezogen"),
                            ("expired", "verfallen"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "Website"),
                            ("phone_assistant", "Telefonassistent"),
                            ("staff", "Praxisteam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_existing_patient", models.BooleanField()),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("statutory", "gesetzlich"),
                            ("private", "privat"),
                            ("self_pay", "Selbstzahler"),
                        ],
                        max_length=16,
                    ),
                ),
                ("patient_first_name", models.CharField(max_length=100)),
                ("patient_last_name", models.CharField(max_length=100)),
                ("patient_date_of_birth", models.DateField()),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=40)),
                ("contact_name", models.CharField(blank=True, max_length=200)),
                ("contact_relationship", models.CharField(blank=True, max_length=100)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("staff_note", models.TextField(blank=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("privacy_notice_version", models.CharField(max_length=40)),
                (
                    "delete_after",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferred_by_requests",
                        to="practice.resource",
                    ),
                ),
                (
                    "appointment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="appointments.appointmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terminanfrage",
                "verbose_name_plural": "Terminanfragen",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "vorgeschlagen"),
                            ("booked", "gebucht"),
                            ("cancelled", "abgesagt"),
                        ],
                        max_length=16,
                    ),
                ),
                ("proposal_expires_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("patient", "Patient"),
                            ("practice", "Praxis"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "cancellation_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("link", "Link in der E-Mail"),
                            ("phone", "Telefon"),
                            ("backoffice", "Backoffice"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_longer_fits", "Termin passt nicht mehr"),
                            ("treated_elsewhere", "anderweitig versorgt"),
                            ("proposal_declined", "Vorschlag abgelehnt"),
                            ("proposal_expired", "Frist für den Vorschlag abgelaufen"),
                            (
                                "proposal_withdrawn",
                                "Vorschlag von der Praxis zurückgezogen",
                            ),
                            ("practice_unavailable", "Ärztin/Arzt verhindert"),
                            ("please_call", "bitte telefonisch melden"),
                            ("not_bookable_online", "nicht online vergebbar"),
                            ("other", "anderer Grund"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "delete_after",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="appointments.appointmentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin",
                "verbose_name_plural": "Termine",
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="practice.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terminressource",
                "verbose_name_plural": "Terminressourcen",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="resources",
            field=models.ManyToManyField(
                related_name="appointments",
                through="appointments.AppointmentResource",
                to="practice.resource",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.appointmenttype",
            ),
        ),
        migrations.CreateModel(
            name="RequestedTimeWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("date", models.DateField()),
                (
                    "part_of_day",
                    models.CharField(
                        choices=[
                            ("morning", "vormittags"),
                            ("afternoon", "nachmittags"),
                            ("any", "egal"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_windows",
                        to="appointments.appointmentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wunschzeitraum",
                "verbose_name_plural": "Wunschzeiträume",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="RequestToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("verify_email", "E-Mail bestätigen"),
                            ("respond_to_proposal", "Vorschlag annehmen oder ablehnen"),
                            ("cancel", "Termin absagen"),
                            ("withdraw", "Anfrage zurückziehen"),
                        ],
                        max_length=24,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="appointments.appointmentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link-Token",
                "verbose_name_plural": "Link-Tokens",
            },
        ),
        migrations.CreateModel(
            name="AppointmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("at", models.DateTimeField()),
                (
                    "actor_kind",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("staff", "Praxisteam"),
                            ("system", "System"),
                            ("assistant", "Telefonassistent"),
                        ],
                        max_length=16,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=16)),
                ("to_status", models.CharField(max_length=16)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_longer_fits", "Termin passt nicht mehr"),
                            ("treated_elsewhere", "anderweitig versorgt"),
                            ("proposal_declined", "Vorschlag abgelehnt"),
                            ("proposal_expired", "Frist für den Vorschlag abgelaufen"),
                            (
                                "proposal_withdrawn",
                                "Vorschlag von der Praxis zurückgezogen",
                            ),
                            ("practice_unavailable", "Ärztin/Arzt verhindert"),
                            ("please_call", "bitte telefonisch melden"),
                            ("not_bookable_online", "nicht online vergebbar"),
                            ("other", "anderer Grund"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="appointments.appointmentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verlaufseintrag",
                "verbose_name_plural": "Verlauf",
                "ordering": ["at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "actor_kind__in",
                                ["patient", "staff", "system", "assistant"],
                            )
                        ),
                        name="appointments_event_actor_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("actor__isnull", False), ("actor_kind", "staff")),
                            models.Q(
                                models.Q(("actor_kind", "staff"), _negated=True),
                                ("actor__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="appointments_event_actor_iff_staff",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="appointmentresource",
            constraint=models.UniqueConstraint(
                fields=("appointment", "resource"), name="appointments_resource_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "unverified",
                            "open",
                            "scheduled",
                            "declined",
                            "withdrawn",
                            "expired",
                        ],
                    )
                ),
                name="appointments_request_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("channel__in", ["web", "phone_assistant", "staff"])),
                name="appointments_request_channel_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("insurance_type__in", ["statutory", "private", "self_pay"])),
                name="appointments_request_insurance_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("channel", "web"), _negated=True),
                    models.Q(("email", ""), _negated=True),
                    _connector="OR",
                ),
                name="appointments_request_web_needs_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "unverified"), _negated=True),
                    models.Q(("email", ""), _negated=True),
                    _connector="OR",
                ),
                name="appointments_request_unverified_needs_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["proposed", "booked", "cancelled"])),
                name="appointments_appointment_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("end__gt", models.F("start"))),
                name="appointments_appointment_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["proposed", "booked"])),
                fields=("request",),
                name="appointments_one_active_appointment_per_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "proposed"), _negated=True),
                    ("proposal_expires_at__isnull", False),
                    _connector="OR",
                ),
                name="appointments_proposal_has_deadline",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancelled_at__isnull", False), ("status", "cancelled")),
                    models.Q(
                        models.Q(("status", "cancelled"), _negated=True),
                        ("cancelled_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="appointments_cancelled_iff_cancelled_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestedtimewindow",
            constraint=models.UniqueConstraint(
                fields=("request", "position"),
                name="appointments_window_unique_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestedtimewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1), ("position__lte", 3)),
                name="appointments_window_position_1_to_3",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestedtimewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(("part_of_day__in", ["morning", "afternoon", "any"])),
                name="appointments_window_part_of_day_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="requesttoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "purpose__in",
                        ["verify_email", "respond_to_proposal", "cancel", "withdraw"],
                    )
                ),
                name="appointments_token_purpose_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="requesttoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purpose__in", ["verify_email", "withdraw"]),
                    ("appointment__isnull", False),
                    _connector="OR",
                ),
                name="appointments_token_appointment_for_appointment_purposes",
            ),
        ),
    ]
