# Generated by Django 5.2.17 on 2026-09-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_patient"),
        ("patients", "0001_initial"),
        ("practice", "0002_opening_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="medical_office_entered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="medical_office_removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("medical_office_removed_at__isnull", True),
                    ("medical_office_entered_at__isnull", False),
                    _connector="OR",
                ),
                name="appointments_removed_only_after_entered",
            ),
        ),
    ]
