# Generated by Django 5.2.17 on 2026-09-27 09:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_medical_office_transfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutgoingMail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=100)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_mails",
                        to="appointments.appointmentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "ausgehende Mail",
                "verbose_name_plural": "Postausgang",
                "indexes": [
                    models.Index(
                        condition=models.Q(("failed_at__isnull", True), ("sent_at__isnull", True)),
                        fields=["next_attempt_at"],
                        name="appointments_outbox_pending",
                    )
                ],
            },
        ),
    ]
