# Generated by Django 5.2.17 on 2026-09-27 01:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0003_patient"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartEntryType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=8, unique=True, verbose_name="Kürzel"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Bezeichnung")),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Kürzel",
                "verbose_name_plural": "Kürzel",
                "ordering": ["position", "code"],
            },
        ),
        migrations.CreateModel(
            name="ChartEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lineage_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "aktuell"),
                            ("superseded", "ersetzt"),
                            ("entered_in_error", "Irrtum"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="Zeitpunkt")),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("typo", "Tippfehler"),
                            ("addition", "Ergänzung"),
                            ("correction", "inhaltliche Korrektur"),
                            ("wrong_patient", "falscher Patient"),
                            ("duplicate", "doppelt erfasst"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=16,
                        verbose_name="Grund",
                    ),
                ),
                (
                    "change_reason_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Erläuterung"),
                ),
                (
                    "is_late_entry",
                    models.BooleanField(default=False, editable=False, verbose_name="Nachtrag"),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("addiction", "Sucht"),
                            ("psychotherapy", "Psychotherapie"),
                            ("restricted", "Sperrvermerk"),
                        ],
                        default="normal",
                        max_length=16,
                        verbose_name="Schutzstufe",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "eingegeben"),
                            ("import_medical_office", "aus Medical Office"),
                            ("speech_summary", "aus der Gesprächsdokumentation"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("encounter_lineage_id", models.UUIDField(db_index=True)),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_versions",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaces",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_by",
                        to="records.chartentry",
                    ),
                ),
                (
                    "entry_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="records.chartentrytype",
                        verbose_name="Kürzel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eintrag",
                "verbose_name_plural": "Einträge",
                "ordering": ["lineage_id", "version"],
                "permissions": [
                    (
                        "view_entered_in_error",
                        "Als Irrtum markierte Kontakte und Einträge sehen",
                    )
                ],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lineage_id", "version"),
                        name="records_chartentry_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "superseded"), _negated=True),
                        fields=("lineage_id",),
                        name="records_chartentry_one_head",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["active", "superseded", "entered_in_error"])
                        ),
                        name="records_chartentry_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "sensitivity__in",
                                ["normal", "addiction", "psychotherapy", "restricted"],
                            )
                        ),
                        name="records_chartentry_sensitivity_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source__in",
                                ["manual", "import_medical_office", "speech_summary"],
                            )
                        ),
                        name="records_chartentry_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("change_reason", ""),
                                ("replaces__isnull", True),
                                ("version", 1),
                            ),
                            models.Q(
                                (
                                    "change_reason__in",
                                    [
                                        "typo",
                                        "addition",
                                        "correction",
                                        "wrong_patient",
                                        "duplicate",
                                        "other",
                                    ],
                                ),
                                ("replaces__isnull", False),
                                ("version__gt", 1),
                            ),
                            _connector="OR",
                        ),
                        name="records_chartentry_reason_from_version_2",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("change_reason", "other"), _negated=True),
                            models.Q(("change_reason_text", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="records_chartentry_other_needs_text",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lineage_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "aktuell"),
                            ("superseded", "ersetzt"),
                            ("entered_in_error", "Irrtum"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("occurred_at", models.DateTimeField(verbose_name="Zeitpunkt")),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("typo", "Tippfehler"),
                            ("addition", "Ergänzung"),
                            ("correction", "inhaltliche Korrektur"),
                            ("wrong_patient", "falscher Patient"),
                            ("duplicate", "doppelt erfasst"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=16,
                        verbose_name="Grund",
                    ),
                ),
                (
                    "change_reason_text",
                    models.CharField(blank=True, max_length=200, verbose_name="Erläuterung"),
                ),
                (
                    "is_late_entry",
                    models.BooleanField(default=False, editable=False, verbose_name="Nachtrag"),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("addiction", "Sucht"),
                            ("psychotherapy", "Psychotherapie"),
                            ("restricted", "Sperrvermerk"),
                        ],
                        default="normal",
                        max_length=16,
                        verbose_name="Schutzstufe",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "eingegeben"),
                            ("import_medical_office", "aus Medical Office"),
                            ("speech_summary", "aus der Gesprächsdokumentation"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("visit", "Besuch in der Praxis"),
                            ("phone", "Telefonat"),
                            ("home_visit", "Hausbesuch"),
                            ("video", "Videosprechstunde"),
                        ],
                        max_length=16,
                        verbose_name="Art",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_versions",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaces",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_by",
                        to="records.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontakt",
                "verbose_name_plural": "Kontakte",
                "ordering": ["lineage_id", "version"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lineage_id", "version"),
                        name="records_encounter_version_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "superseded"), _negated=True),
                        fields=("lineage_id",),
                        name="records_encounter_one_head",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["active", "superseded", "entered_in_error"])
                        ),
                        name="records_encounter_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "sensitivity__in",
                                ["normal", "addiction", "psychotherapy", "restricted"],
                            )
                        ),
                        name="records_encounter_sensitivity_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source__in",
                                ["manual", "import_medical_office", "speech_summary"],
                            )
                        ),
                        name="records_encounter_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("change_reason", ""),
                                ("replaces__isnull", True),
                                ("version", 1),
                            ),
                            models.Q(
                                (
                                    "change_reason__in",
                                    [
                                        "typo",
                                        "addition",
                                        "correction",
                                        "wrong_patient",
                                        "duplicate",
                                        "other",
                                    ],
                                ),
                                ("replaces__isnull", False),
                                ("version__gt", 1),
                            ),
                            _connector="OR",
                        ),
                        name="records_encounter_reason_from_version_2",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("change_reason", "other"), _negated=True),
                            models.Q(("change_reason_text", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="records_encounter_other_needs_text",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["visit", "phone", "home_visit", "video"])),
                        name="records_encounter_kind_valid",
                    ),
                ],
            },
        ),
    ]
