# Generated by Django 5.2.17 on 2026-09-27 04:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_chart_entry_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chartentry",
            options={
                "ordering": ["lineage_id", "version"],
                "permissions": [
                    (
                        "view_entered_in_error",
                        "Als Irrtum markierte Kontakte und Einträge sehen",
                    ),
                    (
                        "view_all_patients",
                        "Akte aller Patienten sehen, ohne Behandlungsteam",
                    ),
                    ("view_addiction", "Einträge der Schutzstufe Sucht sehen"),
                    ("write_normal", "Einträge der Schutzstufe normal schreiben"),
                    ("write_addiction", "Einträge der Schutzstufe Sucht schreiben"),
                    (
                        "write_psychotherapy",
                        "Einträge der Schutzstufe Psychotherapie schreiben",
                    ),
                ],
                "verbose_name": "Eintrag",
                "verbose_name_plural": "Einträge",
            },
        ),
    ]
