# Generated by Django 5.2.17 on 2026-09-26 16:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("family_name", models.CharField(max_length=100, verbose_name="Nachname")),
                ("given_name", models.CharField(max_length=100, verbose_name="Vorname")),
                (
                    "birth_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Geburtsname"),
                ),
                ("title", models.CharField(blank=True, max_length=50, verbose_name="Titel")),
                ("date_of_birth", models.DateField(db_index=True, verbose_name="Geburtsdatum")),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("female", "weiblich"),
                            ("male", "männlich"),
                            ("other", "divers"),
                            ("unknown", "ohne Angabe"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Straße und Hausnummer"
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10, verbose_name="PLZ")),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="Ort")),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="Telefon")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-Mail")),
                (
                    "deceased_on",
                    models.DateField(blank=True, null=True, verbose_name="verstorben am"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
                ("last_contact_on", models.DateField(blank=True, editable=False, null=True)),
                (
                    "retain_until",
                    models.DateField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patienten",
                "ordering": ["family_name", "given_name", "date_of_birth"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sex__in", ["female", "male", "other", "unknown"])),
                        name="patients_patient_sex_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("field", models.CharField(max_length=50)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                (
                    "changed_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verlaufseintrag Stammdaten",
                "verbose_name_plural": "Verlauf Stammdaten",
                "ordering": ["-changed_at", "field"],
            },
        ),
        migrations.CreateModel(
            name="CareTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.localdate)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_team",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitglied im Behandlungsteam",
                "verbose_name_plural": "Behandlungsteam",
                "ordering": ["valid_from"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("valid_until__isnull", True)),
                        fields=("patient", "user"),
                        name="patients_care_team_once_current",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="patients_care_team_until_after_from",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("medical_office", "Patientennummer Medical Office"),
                            ("kvnr", "Krankenversichertennummer"),
                        ],
                        max_length=32,
                        verbose_name="Art",
                    ),
                ),
                ("value", models.CharField(max_length=64, verbose_name="Nummer")),
                ("valid_from", models.DateField(default=django.utils.timezone.localdate)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kennung",
                "verbose_name_plural": "Kennungen",
                "ordering": ["system", "-valid_from"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("system__in", ["medical_office", "kvnr"])),
                        name="patients_identifier_system_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("system", "value"), name="patients_identifier_unique_per_system"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("valid_until__isnull", True)),
                        fields=("patient", "system"),
                        name="patients_identifier_one_current_per_system",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="patients_identifier_until_after_from",
                    ),
                ],
            },
        ),
    ]
