# Generated by Django 5.2.17 on 2026-09-27 04:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentToShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("addiction", "Sucht"),
                            ("psychotherapy", "Psychotherapie"),
                        ],
                        max_length=16,
                        verbose_name="Bereich",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "granted_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="patients.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freigabe",
                "verbose_name_plural": "Freigaben",
                "ordering": ["area", "valid_from"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("area__in", ["addiction", "psychotherapy"])),
                        name="patients_consent_area_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("valid_until__isnull", True)),
                        fields=("patient", "area", "user"),
                        name="patients_consent_once_current",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="patients_consent_until_after_from",
                    ),
                ],
            },
        ),
    ]
