# Generated by Django 5.2.17 on 2026-09-27 09:13

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_consenttoshare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=500, verbose_name="Grund")),
                (
                    "valid_from",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("valid_until", models.DateTimeField(editable=False)),
            ],
            options={
                "verbose_name": "Notfallzugriff",
                "verbose_name_plural": "Notfallzugriffe",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["family_name", "given_name", "date_of_birth"],
                "permissions": [
                    ("restrict_patient", "Sperrvermerk setzen"),
                    ("lift_restriction", "Sperrvermerk aufheben"),
                    ("link_account", "Patient mit einem Konto verknüpfen"),
                ],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patienten",
            },
        ),
        migrations.RemoveConstraint(
            model_name="consenttoshare",
            name="patients_consent_area_valid",
        ),
        migrations.AddField(
            model_name="patient",
            name="is_restricted",
            field=models.BooleanField(default=False, editable=False, verbose_name="Sperrvermerk"),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Konto",
            ),
        ),
        migrations.AlterField(
            model_name="consenttoshare",
            name="area",
            field=models.CharField(
                choices=[
                    ("addiction", "Sucht"),
                    ("psychotherapy", "Psychotherapie"),
                    ("restricted", "Sperrvermerk"),
                ],
                max_length=16,
                verbose_name="Bereich",
            ),
        ),
        migrations.AddConstraint(
            model_name="consenttoshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("area__in", ["addiction", "psychotherapy", "restricted"])),
                name="patients_consent_area_valid",
            ),
        ),
        migrations.AddField(
            model_name="emergencyaccess",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_accesses",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="emergencyaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Konto",
            ),
        ),
        migrations.AddConstraint(
            model_name="emergencyaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="patients_emergency_access_reason_given",
            ),
        ),
        migrations.AddConstraint(
            model_name="emergencyaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_until__gt", models.F("valid_from"))),
                name="patients_emergency_access_until_after_from",
            ),
        ),
    ]
