# Generated by Django 5.2.17 on 2026-09-27 09:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0005_outgoing_mail"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallbackRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=40)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("prescription", "Rezept"),
                            ("referral", "Überweisung"),
                            ("sick_note", "AU"),
                            ("findings", "Befund"),
                            ("doctor_callback", "Rückruf Ärztin/Arzt"),
                            ("cancel_or_move", "Absage/Verschiebung"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "offen"),
                            ("done", "erledigt"),
                            ("expired", "verfallen"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("delete_after", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Rückrufbitte",
                "verbose_name_plural": "Rückrufbitten",
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "category__in",
                                [
                                    "prescription",
                                    "referral",
                                    "sick_note",
                                    "findings",
                                    "doctor_callback",
                                    "cancel_or_move",
                                    "other",
                                ],
                            )
                        ),
                        name="telephony_callback_category_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["open", "done", "expired"])),
                        name="telephony_callback_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reference", ""),
                            ("category", "cancel_or_move"),
                            _connector="OR",
                        ),
                        name="telephony_callback_reference_only_for_cancel",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("closed_at__isnull", True),
                                ("delete_after__isnull", True),
                                ("status", "open"),
                            ),
                            models.Q(
                                ("closed_at__isnull", False),
                                ("delete_after__isnull", False),
                                ("status__in", ["done", "expired"]),
                            ),
                            _connector="OR",
                        ),
                        name="telephony_callback_closed_has_dates",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("duration_seconds", models.PositiveIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("outside_hours", "außerhalb der Öffnungszeiten"),
                            ("overflow", "Überlauf"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("info", "Auskunft"),
                            ("request_created", "Terminanfrage angelegt"),
                            ("callback_requested", "Rückrufbitte angelegt"),
                            ("handed_off", "an das Team verwiesen"),
                            ("emergency_hint", "Notfallhinweis"),
                            ("abandoned", "ohne Anliegen beendet"),
                            ("failed", "technischer Fehler"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "callback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="telephony.callbackrequest",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="appointments.appointmentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anruf",
                "verbose_name_plural": "Anrufe",
                "ordering": ["started_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("mode__in", ["outside_hours", "overflow"])),
                        name="telephony_callrecord_mode_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "outcome__in",
                                [
                                    "info",
                                    "request_created",
                                    "callback_requested",
                                    "handed_off",
                                    "emergency_hint",
                                    "abandoned",
                                    "failed",
                                ],
                            )
                        ),
                        name="telephony_callrecord_outcome_valid",
                    ),
                ],
            },
        ),
    ]
